name: Cargo Test

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run cargo test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      # - name: Install system dependencies for pcsc
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y libpcsclite-dev pkg-config

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Run tests
        run: cargo test --lib --bin ykada --locked --verbose

      - name: Rust format check
        run: cargo fmt --check

      # - name: Install cargo utils
      #   run: cargo install cargo-audit cargo-deny cargo-tarpaulin cargo-chef

      # - name: Run cargo audit
      #   run: cargo audit

      # - name: Run cargo deny
      #   run: cargo deny check

      # - name: Run cargo tarpaulin
      #   run: cargo tarpaulin --fail-under 80
