name: Cargo Test

on:
  push:
    branches:
      - "**"

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install system dependencies for pcsc
        run: |
          sudo apt-get update
          sudo apt-get install -y libpcsclite-dev pkg-config

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build binaries
        run: cargo build --bins --locked

      - name: Run unit tests (lib + bins)
        run: cargo test --lib --bins --locked --verbose

      - name: Rust format check
        run: cargo fmt --check

      - name: Lint with clippy
        run: cargo clippy --all-targets --all-features --locked -- --deny warnings
